﻿<#
.SYNOPSIS
    修复 github.com 无法访问的问题（DNS 解析到的 IP 被当前网络屏蔽）。

.DESCRIPTION
    典型现象：
      * 浏览器打不开 github.com / github.com/settings/tokens
      * git push / git clone 超时
      * 但 api.github.com 却正常

    原因：DNS 把 github.com 解析到了一个在当前网络中被屏蔽的接入 IP
          （实测常见的是 20.205.243.166），而 GitHub 的其他接入 IP 是可用的。

    本脚本会：
      1. 逐个探测候选 IP 的连通性（真实发起 HTTPS 请求，不是 ping）
      2. 选出当前成功率最高、速度最快的那个
      3. 写入 hosts 文件（带 BEGIN/END 标记，可一键完整还原）
      4. 刷新 DNS 缓存并复验

    需要以管理员身份运行。

.PARAMETER CandidateIp
    候选 IP 列表，默认使用实测可用的 GitHub 接入 IP。

.PARAMETER ProbeCount
    每个 IP 的探测次数，默认 4 次。

.PARAMETER Restore
    还原模式：删除本脚本写入的 hosts 记录并刷新 DNS。

.EXAMPLE
    # 方式一：双击同目录下的 fix_github_hosts.bat（会弹出 UAC 确认）
    # 方式二：以管理员身份打开 PowerShell 后执行：
    powershell -ExecutionPolicy Bypass -File D:\leaves\scripts\fix_github_hosts.ps1

.EXAMPLE
    # 还原（恢复系统原始 DNS 行为）
    powershell -ExecutionPolicy Bypass -File D:\leaves\scripts\fix_github_hosts.ps1 -Restore
#>

[CmdletBinding()]
param(
    [string[]]$CandidateIp = @(
        '4.237.22.38', '20.26.156.215', '20.27.177.113',
        '140.82.112.3', '140.82.113.3', '140.82.116.3'
    ),
    [int]$ProbeCount = 4,
    [switch]$Restore
)

$ErrorActionPreference = 'Stop'
$HostsPath = Join-Path $env:SystemRoot 'System32\drivers\etc\hosts'
$MarkBegin = '# >>> leaves-github-fix BEGIN (generated by scripts/fix_github_hosts.ps1)'
$MarkEnd   = '# <<< leaves-github-fix END'
$RawIpForRaw = '185.199.108.133'   # raw.githubusercontent.com 的可用接入 IP

function Assert-Admin {
    $id = [Security.Principal.WindowsIdentity]::GetCurrent()
    $ok = ([Security.Principal.WindowsPrincipal]$id).IsInRole(
        [Security.Principal.WindowsBuiltInRole]::Administrator)
    if (-not $ok) {
        Write-Host ''
        Write-Host '  [×] 需要管理员权限' -ForegroundColor Red
        Write-Host '      请以管理员身份打开 PowerShell 后重新运行：' -ForegroundColor Yellow
        Write-Host ('      powershell -ExecutionPolicy Bypass -File "{0}"' -f $PSCommandPath)
        Write-Host '      或直接双击同目录下的 fix_github_hosts.bat' -ForegroundColor Yellow
        Write-Host ''
        exit 1
    }
}

function New-Backup {
    $stamp = Get-Date -Format 'yyyyMMdd-HHmmss'
    $bak = "$HostsPath.bak-$stamp"
    Copy-Item -LiteralPath $HostsPath -Destination $bak -Force
    Write-Host ("  已备份原 hosts -> {0}" -f $bak)
}

function Test-GithubIp {
    param([string]$Ip, [int]$Times)

    $ok = 0
    $sum = 0.0
    for ($i = 0; $i -lt $Times; $i++) {
        $out = & curl.exe -sS -o NUL --resolve "github.com:443:$Ip" `
                          -w '%{http_code}|%{time_total}' --max-time 10 `
                          'https://github.com/login' 2>$null
        $parts = "$out" -split '\|'
        if ($parts.Count -ge 2 -and $parts[0] -eq '200') {
            $ok++
            $sum += [double]$parts[1]
        }
    }
    $avg = if ($ok -gt 0) { [math]::Round($sum / $ok, 2) } else { -1 }
    return [pscustomobject]@{ Ip = $Ip; Ok = $ok; Total = $Times; Avg = $avg }
}

function Select-BestIp {
    param([string[]]$Ips, [int]$Times)

    Write-Host '  正在探测各候选 IP（真实 HTTPS 请求）...' -ForegroundColor Cyan
    $results = @()
    foreach ($ip in $Ips) {
        Write-Host -NoNewline ("    测试 {0,-16} " -f $ip)
        $r = Test-GithubIp -Ip $ip -Times $Times
        $results += $r
        $mark = if ($r.Ok -eq $r.Total) { '通过' } elseif ($r.Ok -gt 0) { '部分可用' } else { '不可用' }
        $avgText = if ($r.Avg -ge 0) { "$($r.Avg)s" } else { '-' }
        Write-Host ("{0}/{1}  平均 {2}  [{3}]" -f $r.Ok, $r.Total, $avgText, $mark)
    }

    $viable = @($results | Where-Object { $_.Ok -eq $_.Total } | Sort-Object Avg)
    if ($viable.Count -eq 0) {
        $viable = @($results | Where-Object { $_.Ok -gt [math]::Floor($_.Total / 2) } | Sort-Object Avg)
    }
    if ($viable.Count -eq 0) {
        return $null
    }
    return $viable[0]
}

function Remove-ManagedBlock {
    param([string]$Path)

    $lines = @(Get-Content -LiteralPath $Path -ErrorAction SilentlyContinue)
    if ($lines.Count -eq 0) { return }

    $keep = New-Object System.Collections.Generic.List[string]
    $inside = $false
    foreach ($line in $lines) {
        if ($line.Trim() -eq $MarkBegin) { $inside = $true; continue }
        if ($line.Trim() -eq $MarkEnd)   { $inside = $false; continue }
        if (-not $inside) { $keep.Add($line) }
    }
    $enc = New-Object System.Text.UTF8Encoding($false)
    [System.IO.File]::WriteAllLines($Path, $keep, $enc)
}

function Write-ManagedBlock {
    param([string]$Path, [string]$Ip)

    $tab = [char]9
    $block = @(
        '',
        $MarkBegin,
        '# github.com 的默认解析结果在当前网络被屏蔽，这里指向可用的接入点。',
        '# 由 scripts/fix_github_hosts.ps1 自动生成，可随时重新运行以更换 IP。',
        ($Ip + $tab + 'github.com'),
        ($RawIpForRaw + $tab + 'raw.githubusercontent.com'),
        $MarkEnd,
        ''
    )

    # 一次性整体重写，避免 Add-Content 在文件中间插入 BOM
    $lines = New-Object System.Collections.Generic.List[string]
    foreach ($line in @(Get-Content -LiteralPath $Path -ErrorAction SilentlyContinue)) {
        $lines.Add($line)
    }
    foreach ($line in $block) { $lines.Add($line) }

    $enc = New-Object System.Text.UTF8Encoding($false)
    [System.IO.File]::WriteAllLines($Path, $lines, $enc)
}

function Test-After {
    Write-Host '  刷新 DNS 缓存...'
    & ipconfig /flushdns | Out-Null
    Start-Sleep -Milliseconds 800

    Write-Host '  复验（走系统 DNS，即 hosts 生效后的结果）...' -ForegroundColor Cyan
    $code = & curl.exe -sSL -o NUL -w '%{http_code}' --max-time 15 'https://github.com/login' 2>$null
    if ("$code" -eq '200') {
        Write-Host '  [√] github.com 现在可以正常访问了' -ForegroundColor Green
        return $true
    }
    Write-Host ("  [!] 复验返回 {0}：可能生效需要几秒，或该 IP 刚被屏蔽。" -f $code) -ForegroundColor Yellow
    Write-Host '      重新运行本脚本即可自动换一个 IP。' -ForegroundColor Yellow
    return $false
}

# --------------------------------------------------------------------------- #
Assert-Admin
Write-Host ''
Write-Host '=== GitHub 访问修复 ===' -ForegroundColor White

if ($Restore) {
    Write-Host '  还原模式：移除本脚本写入的记录'
    New-Backup
    Remove-ManagedBlock -Path $HostsPath
    & ipconfig /flushdns | Out-Null
    Write-Host '  [√] 已还原，DNS 缓存已刷新' -ForegroundColor Green
    Write-Host ''
    exit 0
}

$best = Select-BestIp -Ips $CandidateIp -Times $ProbeCount
if (-not $best) {
    Write-Host ''
    Write-Host '  [×] 候选 IP 全部不可用，无法通过 hosts 修复。' -ForegroundColor Red
    Write-Host '      建议改用其他网络（如手机热点），' -ForegroundColor Yellow
    Write-Host '      或使用 scripts/push_via_api.py 通过 GitHub API 推送。' -ForegroundColor Yellow
    Write-Host ''
    exit 2
}

Write-Host ''
Write-Host ("  选中 IP：{0}（平均 {1}s）" -f $best.Ip, $best.Avg) -ForegroundColor Green

New-Backup
Remove-ManagedBlock -Path $HostsPath
Write-ManagedBlock -Path $HostsPath -Ip $best.Ip
Write-Host '  已写入 hosts'

if (Test-After) {
    Write-Host ''
    Write-Host '  现在可以打开：https://github.com/settings/tokens/new' -ForegroundColor White
    Write-Host ''
}
